### ISSUE TITLE
depreciated dependencies

### ISSUE THREAD

**Issue by ewkt** [ImSkully/pm2-papertrail-logger#3]
hi! thanks a lot for this package! it's a great and easy way to setup logging with pm2.

while installing it today i got these error messages and just wanted to give you a heads up!

(NPM 10.7.0 & Node 20.15.0)

npm warn deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm warn deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm warn deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm warn deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)

**Comment by ImSkully** [comment]
Thank you for raising this, I've just released [v2.0.0](https://github.com/ImSkully/pm2-papertrail-logger/releases/tag/v2.0.0) which updates all dependencies to their latest stable version!
